module ApRubySdk
  module RefundReason
    CHARGEBACK_AVOIDANCE = 'CHARGEBACK_AVOIDANCE'
    END_USER_ERROR = 'END_USER_ERROR'
    FRAUD = 'FRAUD'
    UNSATISFIED_CUSTOMER = 'UNSATISFIED_CUSTOMER'
    INVALID_TRANSACTION = 'INVALID_TRANSACTION'
  end
end
